### ISSUE TITLE
Feature Request- //expand - ability to expand a region from bedrock to build limit.

### ISSUE THREAD

**Issue by ProsperCraft** [JimiIT92/UniverseGuard#13] opened 2017-10-27 19:32 UTC
With worldguard we would select two corners of a spawn area then //expand vert to set it from bedrock to build limit.  Would love this feature here.

also //expand north 10  for example worked.

**Comment by JimiIT92** [comment] 2017-10-28 19:22
That feature is in working and will be in the next version. The problem is that i'm really really super busy with my work right now and so i don't have that much time to work on UG :/ Also i'm looking how to improve regions and flags management in code, since i don't really like how it is right now. But yeah, this feature will finally be added ;)

**Closed** 2020-02-29 11:47 UTC
